name: Automate Release
on: push
jobs:
  build-project:
    name: Build Win application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Dependecies
        run: npm i
      - name: Generate Application
        run: npm run pack-win
      - name: Upload Content
        uses: actions/upload-artifact@v2
        with:
          name: Application Upload
          path: apps/klelogger-win32-x64

  release-project:
    name: Release WinBuild
    runs-on: ubuntu-latest
    needs: build-project
    steps:
      - name: Download Site Content
        uses: actions/download-artifact@v2
        with:
          name: EBuildWin
      - name: Archive Content
        uses: thedoctor0/zip-release@master
        with:
          filename: win.zip
      - name: Create Github Release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ secrets.run_number }}
          release_name: Release V${{ secrets.run_number }}
      - name: Upload Asset to Github Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }} 
          asset_path: ./win.zip
          asset_name: ELogger-V${{ secrets.run_number }}.zip
          asset_content_type: application/zip
